server:
  port: 9090
spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    compatibility-verifier:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"
    fetchRegistry: true
    registerEureka: true